### ISSUE TITLE
Interpolator fails on singleton dimension

### ISSUE THREAD

**Issue by marceloandrioni** [CNES/pangeo-pyinterp#11] opened 2022-07-18 13:35 UTC
**Describe the bug**

For a 3D variable (time, lat, lon), the interpolation works fine if len(time) > 1, but fails if len(time) == 1 (singleton dimension).

**To Reproduce**

Code and input/output files bellow. The output file `ssh1t_interp.nc` only has NaNs. 

```python
import numpy as np
import xarray as xr

import pyinterp
import pyinterp.fill
import pyinterp.backends.xarray

# infile = '/tmp/ssh2t.nc'   # OK
infile = '/tmp/ssh1t.nc'   # FAIL

outfile = infile.replace('.nc', '_interp.nc')

ds = xr.open_dataset(infile)

# output coords
time = ds['time']

dx = dy = 1 / 10
latitude = np.arange(ds['latitude'].min(), ds['latitude'].max(), dy)
longitude = np.arange(ds['longitude'].min(), ds['longitude'].max(), dx)

coords = dict(time=time, latitude=latitude, longitude=longitude)

# create output dataset with the new coords
ds_new = xr.Dataset(coords)

mx, my, mt = np.meshgrid(*[ds_new[x].values
                           for x in ['longitude', 'latitude', 'time']],
                         indexing='ij')

for var in ds.data_vars:
    print(f'Interpolating {var}')

    interpolator = pyinterp.backends.xarray.Grid3D(ds[var])
    bicubic = interpolator.bicubic(dict(longitude=mx.flatten(),
                                        latitude=my.flatten(),
                                        time=mt.flatten()))
    bicubic = bicubic.reshape(mx.shape).transpose(2, 1, 0)

    ds_new[var] = (list(ds.coords), bicubic, ds.attrs, ds.encoding)

ds_new.to_netcdf(outfile)
ds.close()
```

Input/output files:
[ssh.zip](https://github.com/CNES/pangeo-pyinterp/files/9132241/ssh.zip)

**Expected behavior**

Interpolation for dataarrays with singleton dimension (including time and depth/height dimension) for 3D (time, lat, lon) and 4D (time,depth/height,lat,lon) grids.

Thank you.

**Comment by fbriol** [comment] 2022-07-19 07:20
Thank you for reporting the problem. The problem is fixed in the develop branch.

**Closed by fbriol** 2022-07-19 07:20 UTC
