### ISSUE TITLE
Can't import pyinter.fill

### ISSUE THREAD

**Issue by JuGoCa7** [CNES/pangeo-pyinterp#23] opened 2023-05-18 19:09 UTC
I'm working on Windows 10 and I've installed the Boost C++, Eigen3, GNU Scientific Library, and pybind11 libraries. Then I've proceeded to conda install on the Anacona Prompt the pyinterp library. But when I intended to import some functions, the next occurred:

import pyinterp.fill

This is the complete traceback:
<<
  Cell In[2], line 1
    import pyinterp.fill

  File ~\anaconda3\lib\site-packages\pyinterp\__init__.py:9
    from . import geodetic, geohash, version

  File ~\anaconda3\lib\site-packages\pyinterp\geodetic\__init__.py:9
    from .. import interface

  File ~\anaconda3\lib\site-packages\pyinterp\interface.py:14
    from . import core

ImportError: DLL load failed while importing core: the specified module can not be found.
>>

I've searched online about what DLL file could be missing, but no responses yet.

I would appreciate if you could guide me about what files I might be missing or if it is necessary to uninstall it and reinstall it in a different way, thank you very much in advance

**Comment by fbriol** [comment] 2023-05-19 08:07
The version of the compiler used by conda-forge on Windows has changed. I have rebuilt a new package ([in progress](https://github.com/conda-forge/pyinterp-feedstock/runs/13602958693)). Let me know if this solves your problem.

**Comment by fbriol** [comment] 2023-05-24 16:28
You can try the latest version 2023.5.0 to see if the problem is fixed.

**Comment by treden** [comment] 2023-06-28 08:29
Hi @fbriol, 
Same problem here, even with the latest version 2023.5.0. Is there any fix ?

Here is the pyinterp error (after running a swot_simulator instance in the cmd promp):

File "C:\Users\ytt\AppData\Local\anaconda3\lib\site-packages\swot_simulator\plugins\ssh\aviso.py", line 10, in <module>
        import pyinterp.backends.xarray
      File "C:\Users\ytt\AppData\Local\anaconda3\lib\site-packages\pyinterp\__init__.py", line 9, in <module>
        from . import geodetic, geohash, version
      File "C:\Users\ytt\AppData\Local\anaconda3\lib\site-packages\pyinterp\geodetic\__init__.py", line 9, in <module>
        from .. import interface
      File "C:\Users\ytt\AppData\Local\anaconda3\lib\site-packages\pyinterp\interface.py", line 14, in <module>
        from . import core
    ImportError: DLL load failed while importing core: The specified module could not be found.

Thanks !

**Comment by fbriol** [comment] 2024-02-05 06:15
This problem is usually fixed in the latest release of the library. Don't hesitate to reopen this issue if you find it persists.

**Closed by fbriol** 2024-02-05 06:15 UTC
